steps:
- name: node
  entrypoint: npm
  args: ['install']
- name: node
  entrypoint: npm
  args: ['test']
  env:
    - "CI=true"
  timeout: '120s'
- name: node
  entrypoint: npm
  args: ["run", "create-env"]
  env:
    - 'MY_SECRET_KEY=${_MY_SECRET_KEY}'
    - 'REACT_APP_VERSION=${_REACT_APP_VERSION}'
    - 'REACT_APP_GOOGLE_CLIENT_ID=${_REACT_APP_GOOGLE_CLIENT_ID}'
    - 'MONGO_DRIVER=${_MONGO_DRIVER}'
    - 'FIREBASE_ADMIN=${_FIREBASE_ADMIN}'
    - 'FIREBASE_CONFIG=${_FIREBASE_CONFIG}'
- name: node
  entrypoint: npm
  args: [ 'run', 'build']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'PROD/app.yaml']
  timeout: '1600s'
