version: '3.4'

services:
  reactstarter:
    image: reactstarter
    build: .
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - 3000:3000
    volumes: 
      - .:/usr/src/app
    stdin_open: true  
     
    
